package api

import (
	"errors"
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/Zyling-ai/zyhive/pkg/agent"
	"github.com/Zyling-ai/zyhive/pkg/artifact"
	"github.com/gin-gonic/gin"
)

// mediaHandler serves allowlisted media from loaded agent workspaces.
// Used by the show_image tool to return screenshots/images generated by agents.
type mediaHandler struct {
	manager *agent.Manager
	tickets *artifact.TicketStore
}

var allowedMediaExts = map[string]string{
	".png":  "image/png",
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".gif":  "image/gif",
	".webp": "image/webp",
	".mp4":  "video/mp4",
	".mov":  "video/quicktime",
	".pdf":  "application/pdf",
}

// ServeMedia GET /api/media?id=ARTIFACT_ID&token=ONE_TIME_TOKEN
func (h *mediaHandler) ServeMedia(c *gin.Context) {
	artifactID := c.Query("id")
	token := c.Query("token")
	if artifactID == "" || token == "" {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid media credential"})
		return
	}
	tickets := h.tickets
	if tickets == nil {
		tickets = artifact.DefaultTickets
	}
	filePath, err := tickets.Consume(artifactID, token)
	if err != nil {
		if errors.Is(err, artifact.ErrExpiredTicket) {
			c.JSON(http.StatusGone, gin.H{"error": "media credential expired"})
		} else {
			c.JSON(http.StatusUnauthorized, gin.H{"error": "invalid media credential"})
		}
		return
	}
	filePath, ok := confineToAgentWorkspace(h.manager, filePath)
	if !ok {
		c.JSON(http.StatusForbidden, gin.H{"error": "file is outside an agent workspace"})
		return
	}

	ext := strings.ToLower(filepath.Ext(filePath))
	mimeType, ok := allowedMediaExts[ext]
	if !ok {
		c.JSON(http.StatusForbidden, gin.H{"error": "file type not allowed"})
		return
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "file not found"})
		return
	}

	c.Header("Cache-Control", "private, max-age=300")
	c.Header("Referrer-Policy", "no-referrer")
	c.Data(http.StatusOK, mimeType, data)
}
