package api

import (
	"net/http"
	"os"
	"path/filepath"
	"strings"

	"github.com/Zyling-ai/zyhive/pkg/agent"
	"github.com/gin-gonic/gin"
)

// mediaHandler serves allowlisted media from loaded agent workspaces.
// Used by the show_image tool to return screenshots/images generated by agents.
type mediaHandler struct {
	token   string // auth token (same as API token)
	manager *agent.Manager
}

var allowedMediaExts = map[string]string{
	".png":  "image/png",
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".gif":  "image/gif",
	".webp": "image/webp",
	".mp4":  "video/mp4",
	".mov":  "video/quicktime",
	".pdf":  "application/pdf",
}

// ServeMedia GET /api/media?path=/tmp/screenshot.png[&token=xxx]
// Accepts auth via Authorization header OR ?token= query param
// (query param needed because <img src=""> cannot send custom headers)
func (h *mediaHandler) ServeMedia(c *gin.Context) {
	// Auth: accept header or query param (B002 26.5.10v3: constant-time compare).
	if h.token == "" {
		c.JSON(http.StatusServiceUnavailable, gin.H{"error": "authentication is not configured"})
		return
	}
	auth := c.GetHeader("Authorization")
	qToken := c.Query("token")
	expectedHeader := "Bearer " + h.token
	if !secretsEqual(auth, expectedHeader) && !secretsEqual(qToken, h.token) {
		c.JSON(http.StatusUnauthorized, gin.H{"error": "unauthorized"})
		return
	}

	filePath := c.Query("path")
	if filePath == "" {
		c.JSON(http.StatusBadRequest, gin.H{"error": "path required"})
		return
	}
	filePath, ok := confineToAgentWorkspace(h.manager, filepath.Clean(filePath))
	if !ok {
		c.JSON(http.StatusForbidden, gin.H{"error": "file is outside an agent workspace"})
		return
	}

	ext := strings.ToLower(filepath.Ext(filePath))
	mimeType, ok := allowedMediaExts[ext]
	if !ok {
		c.JSON(http.StatusForbidden, gin.H{"error": "file type not allowed"})
		return
	}

	data, err := os.ReadFile(filePath)
	if err != nil {
		c.JSON(http.StatusNotFound, gin.H{"error": "file not found"})
		return
	}

	c.Header("Cache-Control", "max-age=3600")
	c.Data(http.StatusOK, mimeType, data)
}
